package db

import (
	"kt-ai-studio/internal/config"
	"kt-ai-studio/internal/models"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var DB *gorm.DB

func InitDB(cfg *config.Config) {
	var err error

	// Ensure db directory exists if path contains directory separator
	if dir := filepath.Dir(cfg.DBPath); dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			log.Fatalf("Failed to create database directory: %v", err)
		}
	}

	newLogger := logger.New(
		log.New(os.Stdout, "\r\n", log.LstdFlags), // io writer
		logger.Config{
			SlowThreshold:             time.Second,  // Slow SQL threshold
			LogLevel:                  logger.Error, // Log level - Changed to Error to reduce noise
			IgnoreRecordNotFoundError: true,         // Ignore ErrRecordNotFound error for logger
			ParameterizedQueries:      true,         // Don't include params in the SQL log
			Colorful:                  false,        // Disable color
		},
	)

	// Enable WAL mode for better concurrency
	// PRAGMA journal_mode=WAL;
	// PRAGMA busy_timeout=5000;
	// _pragma=busy_timeout(5000)&_pragma=journal_mode(WAL) is standard for some drivers,
	// but glebarez/sqlite might handle it via DSN params or Exec.
	// Let's use DSN params first, if not enough we run Exec.
	DB, err = gorm.Open(sqlite.Open(cfg.DBPath+"?_pragma=busy_timeout(30000)&_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)"), &gorm.Config{
		Logger: newLogger,
	})
	if err != nil {
		log.Fatalf("无法连接数据库: %v", err)
	}

	// Explicitly set WAL mode and busy timeout to be sure
	if err := DB.Exec("PRAGMA journal_mode=WAL;").Error; err != nil {
		log.Printf("Failed to set WAL mode: %v", err)
	}
	if err := DB.Exec("PRAGMA busy_timeout=30000;").Error; err != nil {
		log.Printf("Failed to set busy_timeout: %v", err)
	}
	if err := DB.Exec("PRAGMA synchronous=NORMAL;").Error; err != nil {
		log.Printf("Failed to set synchronous mode: %v", err)
	}
	if sqlDB, err := DB.DB(); err == nil {
		// Keep SQLite on a single shared connection to avoid writer contention under concurrent tasks.
		sqlDB.SetMaxOpenConns(1)
		sqlDB.SetMaxIdleConns(1)
		sqlDB.SetConnMaxLifetime(0)
	}

	// Auto Migrate Schema
	legacyScenes := DB.Migrator().HasTable("scenes")
	legacyVideos := DB.Migrator().HasTable("videos")
	legacySceneCharacters := DB.Migrator().HasTable("scene_characters")
	if legacyScenes || legacyVideos || legacySceneCharacters {
		log.Println("Dropping legacy scene/video tables and rebuilding unified shots schema...")
		if err := DB.Migrator().DropTable("video_segments", "scene_characters", "videos", "scenes"); err != nil {
			log.Fatalf("Failed to drop legacy scene/video tables: %v", err)
		}
	}

	err = DB.AutoMigrate(
		&models.LLMProvider{},
		&models.LLMUsageBucket{},
		&models.SystemLog{},
		&models.LLMStreamState{},
		&models.SystemSettings{},
		&models.ArtStyle{},
		&models.AutoGenerateTag{},
		&models.GeneralGuideTag{},
		&models.MultiVisualProject{},
		&models.MultiVisualImage{},
		&models.GeneralGuideProject{},
		&models.GeneralGuideReference{},
		&models.GeneralGuideScene{},
		&models.GeneralGuideTransition{},
		&models.AudioCloneProject{},
		&models.AudioCloneCharacter{},
		&models.AudioCloneLine{},
		&models.QwenTTSProject{},
		&models.QwenTTSCharacter{},
		&models.QwenTTSLine{},
		&models.AudioProductionProject{},
		&models.AudioProductionLine{},
		&models.TextToVideoProject{},
		&models.TextToVideoLine{},
		&models.StoreVisitProject{},
		&models.StoreVisitBloggerReference{},
		&models.StoreVisitSpot{},
		&models.StoreVisitDishGenerationItem{},
		&models.Project{},
		&models.AutoGenerateDraft{},
		&models.EpisodeMemory{},
		&models.EpisodeEditorialGuide{},
		&models.ProjectAnchorMemory{},
		&models.Character{},
		&models.Shot{},
		&models.ShotCharacter{},
		&models.VideoSegment{},
		&models.Task{},
	)
	if err != nil {
		log.Fatalf("Failed to migrate database schema: %v", err)
	}
	if !DB.Migrator().HasColumn(&models.Shot{}, "jm_task_id") {
		if err := DB.Migrator().AddColumn(&models.Shot{}, "JMTaskID"); err != nil {
			log.Fatalf("Failed to add jm_task_id to shots: %v", err)
		}
	}
	log.Println("Database initialized successfully")
}

func IsSQLiteBusy(err error) bool {
	if err == nil {
		return false
	}
	message := strings.ToLower(err.Error())
	return strings.Contains(message, "database is locked") ||
		strings.Contains(message, "sqlite_busy") ||
		strings.Contains(message, "sql logic error")
}

func RetryOnBusy(fn func() error) error {
	delays := []time.Duration{
		100 * time.Millisecond,
		250 * time.Millisecond,
		500 * time.Millisecond,
		1 * time.Second,
		2 * time.Second,
	}

	var err error
	for i := 0; i <= len(delays); i++ {
		err = fn()
		if !IsSQLiteBusy(err) {
			return err
		}
		if i == len(delays) {
			break
		}
		time.Sleep(delays[i])
	}
	return err
}
